spring:
  application:
    name: spring-cqrs
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  jwt:
    secret: IUsEyIA1YDstq4tbiccy77AaeB3Jn2HLLMqMhHqXBKtH8S8L34gt8jIayR6JXyUn
    expirationInSeconds: 360000
    issuer: spring-cqrs